use_frameworks!

target 'SBAutoLayout_Example', :exclusive => true do
  pod 'SBAutoLayout', :path => '../'
end

target 'SBAutoLayout_Tests', :exclusive => true do
  pod 'SBAutoLayout', :path => '../'

  
end
